version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - mvn package
  post_build:
    commands:
      - echo "Entered post-build phase"
      - mkdir artifact
      - unzip target/cabs-0.0.1-SNAPSHOT.war -d artifact/
      - mv artifact/WEB-INF WEB-INF
artifacts:
  files:
    - WEB-INF/**/*
  name: artifact
cache:
  paths:
    - '/root/.m2/**/*'
    - 'node_modules/**/*'
